services:
  - docker

before_install:
  - docker build -t coderyihaowang/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run e CI=ture coderyihaowang/multi-client-test npm test

after_success:
  - docker build -t coderyihaowang/multi-client ./client
  - docker build -t coderyihaowang/multi-server ./server
  - docker build -t coderyihaowang/multi-worker ./worker
  - docker build -t coderyihaowang/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push coderyihaowang/multi-client
  - docker push coderyihaowang/multi-server
  - docker push coderyihaowang/multi-worker
  - docker push coderyihaowang/multi-nginx
