services:
  - docker

before_install:
  - docker build -t coderyihaowang/multi-client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true coderyihaowang/multi-client-test npm run test

after_success:
  - docker build -t coderyihaowang/multi-client ./client
  - docker build -t coderyihaowang/multi-server ./server
  - docker build -t coderyihaowang/multi-worker ./worker
  - docker build -t coderyihaowang/multi-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push coderyihaowang/multi-client
  - docker push coderyihaowang/multi-server
  - docker push coderyihaowang/multi-worker
  - docker push coderyihaowang/multi-nginx

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-2-170566615202'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY